FROM maven:3.9.8-eclipse-temurin-21

#VOLUME /tmp

ENV JAVA_OPTS ""

ENV JAR_NAME "labseq-api-0.0.1-SNAPSHOT.jar"

WORKDIR /home/app
COPY . $WORKDIR
RUN mvn clean verify
    
EXPOSE 8080
CMD java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /home/app/target/${JAR_NAME}
# CMD ["java", "$JAVA_OPTS","-Djava.security.egd=file:/dev/./urandom -jar app.jar"]
# CMD [ "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar" ]
# ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar" ]
# CMD ["tail","-f", "/dev/null"]
